source 'https://cdn.cocoapods.org/'

target 'LFLiveKitDemo' do
    platform :ios, '12.0'
    inhibit_all_warnings!
    
    pod 'LFLiveKit-ReplayKit', :path => '../../.'
    pod 'MBProgressHUD'
    pod 'MJExtension'
    pod 'CocoaAsyncSocket'
    pod 'FGRoute'
end

target 'Recoder' do
    platform :ios, '12.0'
    inhibit_all_warnings!
    
    pod 'LFLiveKit-ReplayKit', :path => '../../.'
    pod 'MJExtension'
    pod 'CocoaAsyncSocket'
    
end
